project_id = "yfcfyeueckjqanmtoubt"

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.analyze-semantics]
verify_jwt = false

[functions.scheduled-monitoring]
verify_jwt = false

[functions.apify-scrape]
verify_jwt = false

[functions.apify-status]
verify_jwt = false

[functions.apify-results]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.fanpage-karma]
verify_jwt = false